version: '3'

dotenv: ['.env']

env:
  DOCKER_BUILDKIT: "1"
  PROJECT_NAME: blahufe
  IMG_NAME: sometghing
  REGION: us-east1
  SERVICE_NAME: "fwefwef"

tasks:

  docker:
    cmds:
      - docker build . -t $REGION-docker.pkg.dev/$PROJECT_NAME/$IMG_NAME/$IMG_NAME:latest --ssh default
      - gcloud auth configure-docker $REGION-docker.pkg.dev --account=$GCP_ACCOUNT
      - docker push $REGION-docker.pkg.dev/$PROJECT_NAME/$IMG_NAME/$IMG_NAME:latest
  deploy:
    cmds:
      - gcloud run deploy $SERVICE_NAME --account=$GCP_ACCOUNT --project=$PROJECT --image $REGION-docker.pkg.dev/$PROJECT_NAME/$IMG_NAME/$IMG_NAME:latest --region $REGION --platform managed --allow-unauthenticated
